// Add this to your Layout.jsx file, or create a separate Home.jsx file
import { useAuth } from '../App';

export default function HomePage() {
  const { user } = useAuth();

  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
      {/* Hero Section */}
      <div style={{ textAlign: 'center', padding: '4rem 0' }}>
        <h1 style={{ fontSize: '3rem', marginBottom: '1rem' }}>
          Ace Your Interviews with AI
        </h1>
        <p style={{ fontSize: '1.5rem', color: '#666', marginBottom: '2rem' }}>
          Practice with AI-powered interviews, get instant feedback, and land your dream job.
        </p>
        
        {!user && (
          <a 
            href="/auth"
            style={{
              padding: '1rem 2rem',
              backgroundColor: 'blue',
              color: 'white',
              textDecoration: 'none',
              borderRadius: '5px',
              fontSize: '1.2rem'
            }}
          >
            Get Started - It's Free
          </a>
        )}
      </div>

      {/* Features Section */}
      <div style={{ display: 'flex', gap: '2rem', marginTop: '4rem' }}>
        <div style={{ flex: 1, padding: '2rem', border: '1px solid #ddd', borderRadius: '8px' }}>
          <h3>🎤 AI-Powered Interviews</h3>
          <p>Practice with realistic interview questions generated by AI based on your skills.</p>
        </div>
        
        <div style={{ flex: 1, padding: '2rem', border: '1px solid #ddd', borderRadius: '8px' }}>
          <h3>📊 Detailed Feedback</h3>
          <p>Get comprehensive reports on your answers, strengths, and areas for improvement.</p>
        </div>
        
        <div style={{ flex: 1, padding: '2rem', border: '1px solid #ddd', borderRadius: '8px' }}>
          <h3>🚀 Skill-Based Practice</h3>
          <p>Focus on specific skills and technologies you want to master for your interviews.</p>
        </div>
      </div>

      {/* For Logged-in Users */}
      {user && (
        <div style={{ marginTop: '4rem', padding: '2rem', backgroundColor: '#f5f5f5', borderRadius: '8px' }}>
          <h2>Ready to practice, {user.name}?</h2>
          <p>Start your interview preparation journey now!</p>
          <div style={{ marginTop: '1rem' }}>
            <button style={{ padding: '1rem 2rem', marginRight: '1rem', backgroundColor: 'green', color: 'white', border: 'none', borderRadius: '5px' }}>
              Start Interview
            </button>
            <button style={{ padding: '1rem 2rem', backgroundColor: 'blue', color: 'white', border: 'none', borderRadius: '5px' }}>
              View Reports
            </button>
          </div>
        </div>
      )}

      {/* Testimonials */}
      <div style={{ marginTop: '4rem', textAlign: 'center' }}>
        <h2>Trusted by Job Seekers Worldwide</h2>
        <div style={{ display: 'flex', gap: '2rem', marginTop: '2rem' }}>
          <div style={{ flex: 1 }}>
            <p>"This platform helped me land my dream job at Google!"</p>
            <p>- Sarah, Software Engineer</p>
          </div>
          <div style={{ flex: 1 }}>
            <p>"The AI feedback was incredibly accurate and helpful."</p>
            <p>- Mike, Data Scientist</p>
          </div>
        </div>
      </div>
    </div>
  );
}

// If you create a separate Home.jsx file, export it:
// export default HomePage;